//
//  MediaView.swift
//  Mite
//
//  Created by jpk on 5/2/16.
//  Copyright © 2016 Parker Kirby. All rights reserved.
//

import UIKit

@IBDesignable class MediaView: UIView {
    
    override func drawRect(rect: CGRect) {
        
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()
        
        //// Color Declarations
        let gradientColor = UIColor(red: 1.000, green: 0.000, blue: 0.000, alpha: 1.000)
        
        //// Gradient Declarations
        let gradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [UIColor.blackColor().CGColor, gradientColor.CGColor], [0, 1])!
        
        //// Page-1
        //// Shape Drawing
        let shapePath = UIBezierPath()
        shapePath.moveToPoint(CGPoint(x: 0.26, y: 0.26))
        shapePath.addLineToPoint(CGPoint(x: 0.26, y: 21))
        shapePath.addLineToPoint(CGPoint(x: 21, y: 21))
        shapePath.addLineToPoint(CGPoint(x: 21, y: 0.26))
        shapePath.addLineToPoint(CGPoint(x: 0.26, y: 0.26))
        shapePath.addLineToPoint(CGPoint(x: 0.26, y: 0.26))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 5.59, y: 1.57))
        shapePath.addLineToPoint(CGPoint(x: 15.49, y: 1.57))
        shapePath.addLineToPoint(CGPoint(x: 15.49, y: 2.81))
        shapePath.addLineToPoint(CGPoint(x: 5.59, y: 2.81))
        shapePath.addLineToPoint(CGPoint(x: 5.59, y: 1.57))
        shapePath.addLineToPoint(CGPoint(x: 5.59, y: 1.57))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 15.49, y: 19.69))
        shapePath.addLineToPoint(CGPoint(x: 5.59, y: 19.69))
        shapePath.addLineToPoint(CGPoint(x: 5.59, y: 18.46))
        shapePath.addLineToPoint(CGPoint(x: 15.49, y: 18.46))
        shapePath.addLineToPoint(CGPoint(x: 15.49, y: 19.69))
        shapePath.addLineToPoint(CGPoint(x: 15.49, y: 19.69))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 19.69, y: 19.69))
        shapePath.addLineToPoint(CGPoint(x: 16.79, y: 19.69))
        shapePath.addLineToPoint(CGPoint(x: 16.79, y: 17.15))
        shapePath.addLineToPoint(CGPoint(x: 4.29, y: 17.15))
        shapePath.addLineToPoint(CGPoint(x: 4.29, y: 19.69))
        shapePath.addLineToPoint(CGPoint(x: 1.57, y: 19.69))
        shapePath.addLineToPoint(CGPoint(x: 1.57, y: 1.57))
        shapePath.addLineToPoint(CGPoint(x: 4.29, y: 1.57))
        shapePath.addLineToPoint(CGPoint(x: 4.29, y: 4.11))
        shapePath.addLineToPoint(CGPoint(x: 16.79, y: 4.11))
        shapePath.addLineToPoint(CGPoint(x: 16.79, y: 1.57))
        shapePath.addLineToPoint(CGPoint(x: 19.69, y: 1.57))
        shapePath.addLineToPoint(CGPoint(x: 19.69, y: 19.69))
        shapePath.addLineToPoint(CGPoint(x: 19.69, y: 19.69))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 4.29, y: 15.59))
        shapePath.addLineToPoint(CGPoint(x: 16.79, y: 15.59))
        shapePath.addLineToPoint(CGPoint(x: 16.79, y: 5.67))
        shapePath.addLineToPoint(CGPoint(x: 4.29, y: 5.67))
        shapePath.addLineToPoint(CGPoint(x: 4.29, y: 15.59))
        shapePath.addLineToPoint(CGPoint(x: 4.29, y: 15.59))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 5.59, y: 6.98))
        shapePath.addLineToPoint(CGPoint(x: 15.49, y: 6.98))
        shapePath.addLineToPoint(CGPoint(x: 15.49, y: 14.28))
        shapePath.addLineToPoint(CGPoint(x: 5.59, y: 14.28))
        shapePath.addLineToPoint(CGPoint(x: 5.59, y: 6.98))
        shapePath.addLineToPoint(CGPoint(x: 5.59, y: 6.98))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 2.28, y: 6.98))
        shapePath.addLineToPoint(CGPoint(x: 3.58, y: 6.98))
        shapePath.addLineToPoint(CGPoint(x: 3.58, y: 5.67))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 5.67))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 6.98))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 6.98))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 2.28, y: 9.85))
        shapePath.addLineToPoint(CGPoint(x: 3.58, y: 9.85))
        shapePath.addLineToPoint(CGPoint(x: 3.58, y: 8.54))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 8.54))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 9.85))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 9.85))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 2.28, y: 4.11))
        shapePath.addLineToPoint(CGPoint(x: 3.58, y: 4.11))
        shapePath.addLineToPoint(CGPoint(x: 3.58, y: 2.81))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 2.81))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 4.11))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 4.11))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 2.28, y: 18.46))
        shapePath.addLineToPoint(CGPoint(x: 3.58, y: 18.46))
        shapePath.addLineToPoint(CGPoint(x: 3.58, y: 17.15))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 17.15))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 18.46))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 18.46))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 2.28, y: 15.59))
        shapePath.addLineToPoint(CGPoint(x: 3.58, y: 15.59))
        shapePath.addLineToPoint(CGPoint(x: 3.58, y: 14.28))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 14.28))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 15.59))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 15.59))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 2.28, y: 12.72))
        shapePath.addLineToPoint(CGPoint(x: 3.58, y: 12.72))
        shapePath.addLineToPoint(CGPoint(x: 3.58, y: 11.41))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 11.41))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 12.72))
        shapePath.addLineToPoint(CGPoint(x: 2.28, y: 12.72))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 18.9, y: 11.41))
        shapePath.addLineToPoint(CGPoint(x: 17.59, y: 11.41))
        shapePath.addLineToPoint(CGPoint(x: 17.59, y: 12.72))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 12.72))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 11.41))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 11.41))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 18.9, y: 17.15))
        shapePath.addLineToPoint(CGPoint(x: 17.59, y: 17.15))
        shapePath.addLineToPoint(CGPoint(x: 17.59, y: 18.46))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 18.46))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 17.15))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 17.15))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 18.9, y: 2.81))
        shapePath.addLineToPoint(CGPoint(x: 17.59, y: 2.81))
        shapePath.addLineToPoint(CGPoint(x: 17.59, y: 4.11))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 4.11))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 2.81))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 2.81))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 18.9, y: 14.28))
        shapePath.addLineToPoint(CGPoint(x: 17.59, y: 14.28))
        shapePath.addLineToPoint(CGPoint(x: 17.59, y: 15.59))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 15.59))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 14.28))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 14.28))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 18.9, y: 8.54))
        shapePath.addLineToPoint(CGPoint(x: 17.59, y: 8.54))
        shapePath.addLineToPoint(CGPoint(x: 17.59, y: 9.85))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 9.85))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 8.54))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 8.54))
        shapePath.closePath()
        shapePath.moveToPoint(CGPoint(x: 18.9, y: 5.67))
        shapePath.addLineToPoint(CGPoint(x: 17.59, y: 5.67))
        shapePath.addLineToPoint(CGPoint(x: 17.59, y: 6.98))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 6.98))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 5.67))
        shapePath.addLineToPoint(CGPoint(x: 18.9, y: 5.67))
        shapePath.closePath()
        shapePath.miterLimit = 4;
        
        shapePath.usesEvenOddFillRule = true;
        
        CGContextSaveGState(context)
        shapePath.addClip()
        CGContextDrawLinearGradient(context, gradient, CGPoint(x: 10.63, y: 0.26), CGPoint(x: 10.63, y: 21), CGGradientDrawingOptions())
        CGContextRestoreGState(context)
    }
}